administradores/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login", views.admin_login, name="admin_login"),
    path("crear-admin/", views.create_admin, name="create_admin"),
    path("registrar/cliente", views.create_client, name="create_client"),
    path("search-client/", views.search_client, name="search_client"),
    path('client-details/<int:cliente_id>/', views.expediente_cliente, name='expediente_cliente'),
    path("base", views.base, name="base"),
   
]

clientes/urls.py
from django.urls import path
from . import views

urlpatterns = [

    path('', views.cliente_login, name='cliente_login'),
    path('login/cliente', views.cliente_login, name='cliente_login'),
    path('v2/dashboard/documentos', views.cliente_dashboard_documentos, name='cliente_dashboard'),
    path('upload', views.upload_file, name='upload_file'),
    path('v2/cliente_citas/', views.cliente_citas, name='cliente_citas'),
    path('logout', views.logout_view, name='logout'),
    path('v2/settings/notifications', views.notification_settings, name='notification_settings'),
    path('eliminar-notificacion/<int:id_notificacion>', views.marcar_leida_notificacion, name='eliminar_notificacion'),
    path('v2/dashboard/comentarios', views.comentarios_y_sugerencias, name='comentarios_y_sugerencias'),
    path('v2/notifications', views.notifications, name='notifications'),
    path('book_appointment/', views.book_appointment, name='book_appointment'),
   path('eliminar-notificacion/<int:notificacion_id>/', views.eliminar_notificacion, name='eliminar_notificacion'),
]

v2rcx_client_web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
   
    path('', include('clientes.urls')),
    path('v2admin/', include('administradores.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administradores/models.py
from django.db import models

# Create your models here.
class adminNotification(models.Model):
    texto = models.CharField(max_length=10)

clientes/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone


class CustomUser(AbstractUser):
    email = models.EmailField(
        ("email address"), unique=True
    )  # Asegúrate de que el email sea único
    is_admin = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    nombre = models.CharField(max_length=100, unique=True)
    # Elimina el username de los campos requeridos
    def __str__(self):
        return self.email


class Documento(models.Model):
    TIPO_DOCUMENTO_CHOICES = [
        ("INE_FRENTE", "Frente de INE"),
        ("INE_REVERSO", "Reverso de INE"),
        ("CONSTANCIA_FISCAL", "Constancia fiscal"),
        ("COMPROBANTE_DOMICILIO", "Comprobante domicilio"),
        ("COMPROBANTE_INGRESOS", "Comprobante ingresos"),
        ("CURP", "curp"),
    ]

    ESTADOS = [
        ("SUBIDO", "subido"),
        ("APROBADO", "Aprobado"),
        ("RECHAZADO", "Rechazado"),
    ]
    archivo = models.FileField(upload_to="documentos/")
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tipo_documento = models.CharField(max_length=100, choices=TIPO_DOCUMENTO_CHOICES)
    estado = models.CharField(max_length=20, choices=ESTADOS, default="SUBIDO")
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    activo = models.BooleanField(default=True)

    def __str__(self) -> str:
        return f"{self.usuario} {self.tipo_documento} {self.estado}"


# NOTIFICACIONES DEL USUARIO
class UserNotificationSettings(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    receive_notifications = models.BooleanField(default=True)
    notify_document_status = models.BooleanField(default=False)
    notify_appointment_confirmation = models.BooleanField(default=False)
    notify_appointment_reminder = models.BooleanField(default=False)
    credit_response = models.BooleanField(default=True)
    plates_status = models.BooleanField(default=True)
    unit_details = models.BooleanField(default=True)
    payments_confirmations = models.BooleanField(default=True)

    def __str__(self):
        return f"Notificaciones para {self.user.username}"


class Notificacion(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    mensaje = models.TextField()
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    leida = models.BooleanField(default=False)

    def __str__(self):
        return f"Notificación para {self.usuario.username}: {self.mensaje}"


class AppointmentType(models.Model):
    name = models.CharField(max_length=100)
    duration = models.DurationField()

    def __str__(self):
        return self.name


class Appointment(models.Model):
    usuario = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    appointment_type = models.ForeignKey(AppointmentType, on_delete=models.CASCADE)
    scheduled_time = models.DateTimeField()
    end_time = models.DateTimeField()

    def save(self, *args, **kwargs):
        # Asumimos una duración fija de 1 hora, ajusta según sea necesario
        self.end_time = self.scheduled_time + timezone.timedelta(hours=1)
        super(Appointment, self).save(*args, **kwargs)

    def __str__(self):
        return f"Cita para {self.usuario}"

administradores/forms.py
from django import forms
from clientes.models import CustomUser, Documento
import uuid
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError

class AdminLoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'autofocus': True,
        'class': 'login-input',
        'placeholder': 'Correo electrónico'
    }))
    password = forms.CharField(label ='Contraseña',widget=forms.PasswordInput(attrs={
        'class': 'login-input',
        'placeholder': 'Contraseña'
    }))

class AdminRegistrationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['nombre', 'email', 'phone_number', 'is_admin', 'password']


    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.username = self.generate_unique_username()  # Marcamos automáticamente al usuario como administrador
        if commit:
            user.save()
        return user
    
class ClienteRegistrationForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['nombre', 'email', 'phone_number']  # Cambiado de 'username' a 'nombre'

class DocumentoForm(forms.ModelForm):
    class Meta:
        model = Documento
        fields = ['estado']

administradores/views.py
from django.forms import formset_factory
from django.shortcuts import render
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import user_passes_test, login_required
from .forms import AdminRegistrationForm, AdminLoginForm, ClienteRegistrationForm
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from clientes.models import CustomUser, Documento
import uuid
from .forms import DocumentoForm
import requests
from dateutil import parser
from django.utils import timezone

# LOGINS Y CREACION DE CUENTAS


def admin_login(request):
    if request.method == "POST":
        form = AdminLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get("email")
            password = form.cleaned_data.get("password")
            user = authenticate(
                request,
                username=email,
                password=password,
                backend="administradores.backends.EmailAuthenticationBackend",
            )

            if user is not None and user.is_admin:
                login(request, user)
                return redirect("search_client")
            else:
                form.add_error(
                    None, "Credenciales inválidas o el usuario no es administrador."
                )
        else:
            print("Errores del formulario:", form.errors)
    else:
        form = AdminLoginForm()

    return render(request, "admin_login.html", {"form": form})


@user_passes_test(lambda u: u.is_superuser)
def create_admin(request):
    if request.method == "POST":
        form = AdminRegistrationForm(request.POST)
        if form.is_valid():
            print("Form data:", form.cleaned_data)

            form.save()
            return redirect("create_client")
    else:
        form = AdminRegistrationForm()
    return render(request, "create_admin.html", {"form": form})


def generate_unique_username(nombre):
    """Genera un nombre de usuario único a partir del nombre."""
    # Eliminar espacios y convertir a minúsculas
    base_username = nombre.replace(" ", "").lower()
    unique_username = base_username + uuid.uuid4().hex[:6].lower()

    while CustomUser.objects.filter(username=unique_username).exists():
        unique_username = base_username + uuid.uuid4().hex[:6].lower()

    return unique_username


@user_passes_test(lambda u: u.is_staff)
def create_client(request):
    if request.method == "POST":
        form = ClienteRegistrationForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]
            phone_number = form.cleaned_data["phone_number"]

            # Verificar si el correo ya está en uso
            if CustomUser.objects.filter(email=email).exists():
                form.add_error("email", "Este correo electrónico ya está en uso.")

            # Verificar si el número de teléfono ya está en uso
            elif CustomUser.objects.filter(phone_number=phone_number).exists():
                form.add_error(
                    "phone_number", "Este número de teléfono ya está en uso."
                )

            else:
                try:
                    new_user = form.save(commit=False)
                    new_user.is_admin = False
                    new_user.username = generate_unique_username(
                        form.cleaned_data["nombre"]
                    )
                    new_user.set_password(
                        "some_default_password"
                    )  # Considera un método más seguro para las contraseñas
                    new_user.save()
                    return redirect("cliente_login")
                except IntegrityError:
                    form.add_error("nombre", "Este nombre ya está en uso.")
        # Si hay errores, se vuelve a renderizar el formulario con ellos
        return render(request, "create_client.html", {"form": form})

    else:
        form = ClienteRegistrationForm()
        return render(request, "create_client.html", {"form": form})


# FUNCIONALIDAD DE DASHBOARD PARA VENDEDORES
# Función para obtener los datos del cliente usando el email del usuario logueado


@user_passes_test(lambda u: u.is_staff)
def search_client(request):
    query = request.GET.get("q", "")
    clients = CustomUser.objects.filter(nombre__icontains=query) if query else []
    return render(request, "search_client.html", {"clients": clients})


def fetch_client_by_email(email):
    api_url = (
        "https://lbvj22e1he.execute-api.us-east-1.amazonaws.com/dev/clients/query/"
    )
    headers = {
        "Content-Type": "application/json",
        "x-api-key": "IUPDlxEc2i2xxCYpmmnGL2JmqhVRkQba1n9Tbl6B",
    }
    response = requests.get(f"{api_url}{email}/", headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        return None


@user_passes_test(lambda u: u.is_staff)
def expediente_cliente(request, cliente_id):
    documentos_activos = Documento.objects.filter(usuario_id=cliente_id, activo=True)
    cliente = get_object_or_404(CustomUser, pk=cliente_id)

    if request.method == "POST":
        documento_id = request.POST.get("doc_id")
        documento = get_object_or_404(Documento, pk=documento_id, activo=True)
        form = DocumentoForm(
            request.POST, instance=documento, prefix="doc_" + str(documento_id)
        )

        if form.is_valid():
            form.save()
            return redirect("expediente_cliente", cliente_id=cliente_id)

    documentos_forms = [
        (
            documento,
            DocumentoForm(instance=documento, prefix="doc_" + str(documento.id)),
        )
        for documento in documentos_activos
    ]

    client_data = fetch_client_by_email(cliente.email)

    tipo_evento_mapa = {
        "document_upload": "Subida de Documento",
        "appointment_generation": "Generación de Cita",
        "bitacora_venta_update": "Actualización en bitacora de ventas",
        # Agrega otros mapeos según sea necesario
    }

    event_source_mapa = {
        "Bitacora_de_ventas": "Bitacora de ventas",
    }

    campo_bitacora_mapa = {
        "ESTATUS": "Estatus de crédito",
    }
    tipo_documento_mapa = {
        "CONSTANCIA_FISCAL": "Constancia fiscal",
        "CURP": "CURP",
        "INE_FRENTE": "Frente de INE",
        "INE_REVERSO": "Reverso de INE" , 
    }

    eventos = []
    if client_data:
        client_id = client_data.get("client_id")
        events_api_url = f"https://lbvj22e1he.execute-api.us-east-1.amazonaws.com/dev/clients/{client_id}/events/"
        client_info_url = f"https://lbvj22e1he.execute-api.us-east-1.amazonaws.com/dev/clients/{client_id}/"
        headers = {
            "Content-Type": "application/json",
            "x-api-key": "IUPDlxEc2i2xxCYpmmnGL2JmqhVRkQba1n9Tbl6B",
        }
        client_info_response = requests.get(client_info_url, headers=headers)
        client_info = {}
        if client_info_response.status_code == 200:
            client_info = client_info_response.json()
        events_response = requests.get(events_api_url, headers=headers)
        if events_response.status_code == 200:
            raw_eventos = events_response.json().get("events", [])
            for evento in raw_eventos:
                event_data = evento.get("event_data", {})
                formatted_start = None
                formatted_end = None
                if "scheduled_start" in event_data:
                    formatted_start = timezone.localtime(
                        parser.parse(event_data["scheduled_start"])
                    ).strftime("%Y-%m-%d %H:%M")
                if "scheduled_end" in event_data:
                    formatted_end = timezone.localtime(
                        parser.parse(event_data["scheduled_end"])
                    ).strftime("%Y-%m-%d %H:%M")

                eventos.append(
                    {
                        "event_type": tipo_evento_mapa.get(
                            evento["event_type"], evento["event_type"]
                        ),
                        "timestamp": timezone.localtime(
                            parser.parse(evento["timestamp"])
                        ).strftime("%Y-%m-%d %H:%M"),
                        "event_data": {
                            "concept": event_data.get("concept"),
                            "type": event_data.get("type"),
                            "scheduled_start": formatted_start,
                            "scheduled_end": formatted_end,
                            "documento": tipo_documento_mapa.get(event_data.get("document"), event_data.get("document")),
                            "file_size": event_data.get("file_size"),
                            "sheetName": event_data.get("sheetName"),
                            
                            "column": campo_bitacora_mapa.get(
                                event_data.get("column"), event_data.get("column")
                            ),
                            "value": event_data.get("value"),
                        },
                        "tipo": evento["event_type"],
                        "event_source": event_source_mapa.get(
                            evento["event_source"], evento["event_source"]
                        ),
                    }
                )

    context = {
        "documentos_forms": documentos_forms,
        "cliente_id": cliente_id,
        "eventos": eventos,
        'client_info': client_info,
    }

    return render(request, "expediente_cliente.html", context)


def base(request):
    return render(request, "base_admin.html")
 

administradores/templates/expediente_cliente.html
{% extends 'base_admin.html' %}
{% load static %}

{% block content %}
<div class="client-info-container">
    <h2>Expediente del cliente</h2>
    <p>Nombre: <strong>{{ client_info.name }}</strong></p>
    <p>Número: <strong>{{ client_info.number }}</strong></p>
    <p>Unidad de interés: <strong>{{ client_info.unidad_de_interes }}</strong></p>
    <p>Vendedor asignado: <strong>{{ client_info.vendedor_asignado }}</strong></p>
    <!-- Agregar más detalles según sea necesario -->
</div>
<div class="documentos-container">
    <div id="spinner" class="spinner"></div>
    <h2>Documentos subidos</h2>
    <div class="table-responsive">
        <table class="documentos-table">
            <thead>
                <tr>
                    <th>Descargar</th>
                    <th>Tipo de documento</th>
                    <th>Correo</th>
                    <th>Nombre</th>
                    <th>Cambiar Estado</th>
                </tr>
            </thead>
            <tbody>
                {% for documento, form in documentos_forms %}
                    <tr>
                        <td><a href="{{ documento.archivo.url }}" download>Descargar</a></td>
                        <td>{{ documento.get_tipo_documento_display }}</td>
                        <td>{{ documento.usuario.email }}</td>
                        <td>{{ documento.usuario.nombre }}</td>
                        <td>
                            <form method="post" action="{% url 'expediente_cliente' cliente_id %}" class="document-form">
                                {% csrf_token %}
                                {{ form.estado }}
                                <input type="hidden" name="doc_id" value="{{ documento.id }}">
                                <button class="button" type="submit">Actualizar</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
<div class="eventos-container">
    <h2 class="section-heading">Eventos del Cliente</h2>
    <div class="eventos-list">
        {% for evento in eventos %}
            <div class="evento-item">
                <div class="evento-header" onclick="toggleEventoDetails(this)">
                    <h6 class="evento-title" style="color: white;">{{ evento.event_type | title }}</h6>
                    <span class="evento-icon">+</span>
                </div>
                <div class="evento-details" style="display: none;">
                    <p class="evento-timestamp">Fecha del evento: <strong>{{ evento.timestamp}}</strong></p>
                    <p class="evento-concept">Fuente del evento: <strong>{{ evento.event_source  }}</strong></p>
                    <!-- Aquí comienza la lógica condicional para mostrar detalles adicionales -->
                    {% if evento.tipo == 'appointment_generation' %}
                        <p class="evento-concept">Concepto del evento: <strong>{{ evento.event_data.concept | title }}</strong></p>
                        <p class="evento-detail">Tipo de cita: <strong>{{ evento.event_data.type | title }}</strong></p>
                        <p class="evento-detail">Horario de la cita: Del <strong>{{ evento.event_data.scheduled_start }}</strong> al <strong>{{ evento.event_data.scheduled_end }}</strong></p>
                        <!-- Añadir más detalles específicos para el tipo de evento de cita -->
                    {% elif evento.tipo == 'document_upload' %}
                        <p class="evento-concept">Concepto del evento: <strong>{{ evento.event_data.concept | title }}</strong></p>
                        <p class="evento-detail">Tipo de documento: <strong>{{ evento.event_data.documento  }}</strong></p>
                        <p class="evento-detail">Tamaño de Archivo: <strong>{{ evento.event_data.file_size }}</strong> Bytes</p>
                        <!-- Añadir más detalles específicos para el tipo de evento de subida de documento -->
                    {% elif evento.tipo == 'bitacora_venta_update' %}
                        <p class="evento-concept">Nombre de la hoja: <strong>{{ evento.event_data.sheetName }}</strong></p>
                        <p class="evento-concept">Campo Actualizado: <strong>{{ evento.event_data.column }}</strong></p>
                        <p class="evento-concept">Nuevo valor: <strong>{{ evento.event_data.value }}</strong></p>
                    {% else %}

                    {% endif %}
                    <!-- Aquí termina la lógica condicional -->
                </div>
            </div>
        {% empty %}
            <p>No hay eventos registrados para este cliente.</p>
        {% endfor %}
    </div>
</div>
<button id="scrollToTopButton" onclick="scrollToTop()" style="display: none;">↑ Subir</button>
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
    // Selecciona todos los formularios con la clase 'document-form'
        const forms = document.querySelectorAll('.document-form');
        const spinner = document.getElementById('spinner');
        
        forms.forEach(form => {
            form.onsubmit = function() {
                // Muestra el spinner
                spinner.style.display = 'block';
            };
        });
    });

    function toggleEventoDetails(header) {
    const details = header.nextElementSibling;
    const icon = header.querySelector('.evento-icon');
    details.style.display = details.style.display === 'none' ? 'block' : 'none';
    icon.textContent = icon.textContent === '+' ? '-' : '+';
}
function scrollToTop() {
        window.scrollTo({top: 0, behavior: 'smooth'});
    }

window.onload = function() {
    window.onscroll = function() {
        var scrollButton = document.getElementById('scrollToTopButton');
        
        if (document.body.scrollTop > 6 || document.documentElement.scrollTop > 6) {
            scrollButton.style.display = 'block';
        } else {
            scrollButton.style.display = 'none';
        }
    };
};
</script>
<style>
    /* Estilos para la sección de documentos */
.documentos-container {
    max-width: 800px;
    margin: 0 auto;
    padding: 40px 20px;
    background: #fff;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    min-width: 70%;
    
}
.documentos-container h2 {
    border-bottom: 2px solid #0E2059;
    padding-bottom: 25px;
    margin-bottom: 40px;
}

.table-responsive {
    overflow-x: auto;
}

.documentos-table {
    width: 100%;
    border-collapse: collapse;
     /* Asegura que la tabla no se expanda más allá del contenedor */
}

/* Estilos para la sección de eventos */
.eventos-container {
    margin: 20px auto;
    padding: 15px;
    background-color: #f7f7f7;
    border-radius: 8px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
    max-width: 800px;
    min-width: 70%;
}

.section-heading {
    font-size: 24px;
    color: #333;
    margin-bottom: 20px;
    
}

.eventos-list {
    list-style: none;
    padding: 0;
}

.evento-item {
    background-color: #ffffff;
    border-radius: 8px;
    margin-bottom: 10px;
    overflow: hidden;
    transition: box-shadow 0.6s ease-in-out;
}

.evento-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 10px 15px;
    background-color: #0E2059;
    color: #ffffff;
    cursor: pointer;
}

.evento-header:hover {
    background-color: #003366;
}

.evento-icon {
    font-size: 24px;
}

.evento-title {
    margin: 0;
    font-weight: normal;
}

.evento-details {
    padding: 15px;
    display: none;
    border-top: 1px solid #eeeeee;
}

.evento-timestamp, .evento-concept {
    margin: 5px 0;
}

/* Estilos generales para botones y formularios */
button {
    padding: 8px 15px;
    background-color: #d53249;
    color: white;
    border: none;
    border-radius: 4px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s;
}

button:hover {
    background-color: #004494;
}

form button[type="submit"] {
    margin-top: 10px;
    width: 100%;
}

select, input[type="text"], input[type="email"] {
    padding: 8px;
    margin-bottom: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
    color: #333;
    background-color: white;
    cursor: pointer;
    width: calc(100% - 20px);
    box-sizing: border-box;
}

/* Estilos para las tablas de documentos y detalles de eventos */
.documentos-table thead, .evento-details-table thead {
    background-color: #d53249;
    color: white;
}

.documentos-table th, .documentos-table td, .evento-details-table th, .evento-details-table td {
    padding: 10px;
    text-align: left;
    border: 1px solid #ddd;
}

/* Estilos para el spinner de carga */
.spinner {
    border: 4px solid rgba(0, 0, 0, 0.1);
    width: 50px;
    height: 50px;
    border-radius: 50%;
    border-left-color: #d53249;
    animation: spin 1s ease infinite;
    position: fixed;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    display: none;
}

.client-info-container {
    max-width: 800px;
    margin: 20px auto;
    padding: 20px;
    background: #fff;
    border-radius: 10px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    min-width: 70%;
}

.client-info-container h2 {
    color: #0E2059; /* Un color que combine con el tema */
    border-bottom: 2px solid #0E2059; /* Línea decorativa bajo el título */
    padding-bottom: 10px;
    margin-bottom: 20px;
}

.client-info-container p {
    font-size: 16px;
    color: #333; /* Color oscuro para el texto */
    margin: 10px 0; /* Espacio vertical entre cada parrafo */
    padding-left: 10px; /* Espacio a la izquierda para alinear con el título */
}

/* Añadir estilos para etiquetas fuertes si se usan dentro de los párrafos */
.client-info-container strong {
    font-weight: bold;
    color: #0E2059;
}

#scrollToTopButton {
    position: fixed; /* Fijar el botón en la página */
    bottom: 20px; /* Espacio desde la parte inferior */
    right: 20px; /* Espacio desde la parte derecha */
    padding: 10px 15px;
    background-color: #0E2059; /* Color de fondo */
    color: white; /* Color del texto */
    border: none; /* Sin borde */
    border-radius: 4px; /* Bordes redondeados */
    font-size: 16px; /* Tamaño de la fuente */
    cursor: pointer; /* Cursor en forma de mano */
    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.3); /* Sombra para el botón */
    z-index: 1000; /* Asegurarse de que esté sobre otros elementos */
}

#scrollToTopButton:hover {
    background-color: #003366; /* Color al pasar el ratón */
}

/* Animación del spinner */
@keyframes spin {
    0% { transform: rotate(0deg); }
    100% { transform: rotate(360deg); }
}

/* Estilos responsivos para vistas más pequeñas */
@media (max-width: 768px) {
    .documentos-table, .evento-details-table {
        font-size: 14px;
    }

    .table-responsive {
        overflow-x: scroll;
    }
}
</style>

{% endblock %}